In [ ]:
!pip install gdown
!gdown --fuzzy "https://drive.google.com/file/d/150IkSQip5hQelhY-Upy-g741uLlvx4MZ/view?usp=sharing"

Collecting gdown
  Downloading gdown-5.2.0-py3-none-any.whl (18 kB)
Collecting filelock
  Downloading filelock-3.20.0-py3-none-any.whl (16 kB)
Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 2.4 MB/s eta 0:00:00a 0:00:01
Collecting requests[socks]
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.7/64.7 kB 2.4 MB/s eta 0:00:00
Collecting tqdm
  Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=4.0.0 in /Users/karthikreddy/.pyenv/versions/3.10.13/lib/python3.10/site-packages (from beautifulsoup4->gdown) (4.15.0)
Collecting soupsieve>=1.6.1
  Downloading soupsieve-2.8-py3-none-any.whl (36 kB)
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 2.1 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.6.0-py3-none-any.whl (131 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 131.1/131.1 kB 3.8 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2025.11.12-py3-none-any.whl (159 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 159.4/159.4 kB 1.3 MB/s eta 0:00:00a 0:00:01
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.4-cp310-cp310-macosx_10_9_universal2.whl (209 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 4.2 MB/s eta 0:00:0000:01
Collecting PySocks!=1.5.7,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Installing collected packages: urllib3, tqdm, soupsieve, PySocks, idna, filelock, charset_normalizer, certifi, requests, beautifulsoup4, gdown
Successfully installed PySocks-1.7.1 beautifulsoup4-4.14.3 certifi-2025.11.12 charset_normalizer-3.4.4 filelock-3.20.0 gdown-5.2.0 idna-3.11 requests-2.32.5 soupsieve-2.8 tqdm-4.67.1 urllib3-2.6.0

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: pip install --upgrade pip
Downloading...
From (original): https://drive.google.com/uc?id=150IkSQip5hQelhY-Upy-g741uLlvx4MZ
From (redirected): https://drive.google.com/uc?id=150IkSQip5hQelhY-Upy-g741uLlvx4MZ&confirm=t&uuid=548340cd-b9e4-4e48-b218-80433bbf7b63
To: /Users/karthikreddy/Desktop/Crop_market_price_predictor/merged_crop_data_with_weather.csv
100%|████████████████████████████████████████| 517M/517M [02:13<00:00, 3.88MB/s]

In [5]:
!pip install pandas numpy scikit-learn matplotlib seaborn tqdm --quiet

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: pip install --upgrade pip

In [6]:
import pandas as pd
_df = pd.read_csv("merged_crop_data_with_weather.csv")
_df.info()
_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2709857 entries, 0 to 2709856
Data columns (total 23 columns):
 #   Column           Dtype
---  ------           -----
 0   date             object
 1   Commodity        object
 2   CropGroup        object
 3   State            object
 4   Mandi            object
 5   Arrivals         float64
 6   UnitOfArrivals   object
 7   ModalPrice       float64
 8   MinPrice         float64
 9   MaxPrice         float64
 10  UnitOfPrice      object
 11  Variety          object
 12  Grade            object
 13  market_clean     object
 14  district_name    object
 15  state_id         int64
 16  temp_avg         float64
 17  temp_max         float64
 18  temp_min         float64
 19  rainfall         float64
 20  humidity         float64
 21  solar_radiation  float64
 22  wind_speed       float64
dtypes: float64(11), int64(1), object(11)
memory usage: 475.5+ MB

,date,Commodity,CropGroup,State,Mandi,Arrivals,UnitOfArrivals,ModalPrice,MinPrice,MaxPrice,...,market_clean,district_name,state_id,temp_avg,temp_max,temp_min,rainfall,humidity,solar_radiation,wind_speed
0,2024-01-01,Onion,Vegetables,Bihar,Bahadurganj APMC,4.0,Metric Tonnes,4100.0,4000.0,4200.0,...,BAHADURGANJ APMC,Kishanganj,5,13.96,21.72,8.22,0.0,72.05,6.05,1.57
1,2024-01-01,Onion,Vegetables,Bihar,Barahat APMC,4.0,Metric Tonnes,3500.0,3000.0,4000.0,...,BARAHAT APMC,Banka,5,13.93,21.52,7.95,0.0,69.86,10.69,1.57
2,2024-01-01,Onion,Vegetables,Bihar,Bhagwanpur Mandi APMC,15.0,Metric Tonnes,4100.0,4000.0,4200.0,...,BHAGWANPUR MANDI APMC,Muzaffarpur,5,15.47,24.23,8.86,0.0,54.51,5.38,1.47
3,2024-01-01,Onion,Vegetables,Bihar,Danapur APMC,30.0,Metric Tonnes,3000.0,2800.0,3200.0,...,DANAPUR APMC,Patna,5,15.19,23.63,7.64,0.0,49.75,6.39,1.44
4,2024-01-01,Onion,Vegetables,Bihar,"Gerabari, Korha Block APMC",4.0,Metric Tonnes,4900.0,4800.0,5000.0,...,GERABARI KORHA BLOCK APMC,Kaithar,5,14.39,21.85,8.98,0.0,74.98,8.25,1.65

In [7]:
# https://drive.google.com/file/d/17ho7AGLkb0uFXwBmOy752zh5-iSGlusy/view?usp=sharing

file_id = "17ho7AGLkb0uFXwBmOy752zh5-iSGlusy"
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

latlon = pd.read_csv(download_url)
latlon = latlon.rename(columns={"district": "district_name"})
print("Rows:", len(latlon))
print("Columns:", latlon.columns.tolist())
latlon.info()
zero_coords = latlon[(latlon["lat"] == 0) | (latlon["lon"] == 0)]
len(zero_coords)
latlon.head()

Rows: 554
Columns: ['district_name', 'lat', 'lon']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 554 entries, 0 to 553
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   district_name  554 non-null    object
 1   lat            554 non-null    float64
 2   lon            554 non-null    float64
dtypes: float64(2), object(1)
memory usage: 13.1+ KB

  district_name    lat    lon
0    Kishanganj  25.67  86.93
1         Banka  24.88  86.92
2   Muzaffarpur  26.12  85.38
3         Patna  25.42  85.17
4       Kaithar  25.55  87.57

In [8]:
df = _df.merge(
    latlon[["district_name", "lat", "lon"]],
    on="district_name",
    how="left"
)

In [10]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2748688 entries, 0 to 2748687
Data columns (total 25 columns):
 #   Column           Dtype
---  ------           -----
 0   date             object
 1   Commodity        object
 2   CropGroup        object
 3   State            object
 4   Mandi            object
 5   Arrivals         float64
 6   UnitOfArrivals   object
 7   ModalPrice       float64
 8   MinPrice         float64
 9   MaxPrice         float64
 10  UnitOfPrice      object
 11  Variety          object
 12  Grade            object
 13  market_clean     object
 14  district_name    object
 15  state_id         int64
 16  temp_avg         float64
 17  temp_max         float64
 18  temp_min         float64
 19  rainfall         float64
 20  humidity         float64
 21  solar_radiation  float64
 22  wind_speed       float64
 23  lat              float64
 24  lon              float64
dtypes: float64(13), int64(1), object(11)
memory usage: 524.3+ MB

,date,Commodity,CropGroup,State,Mandi,Arrivals,UnitOfArrivals,ModalPrice,MinPrice,MaxPrice,...,state_id,temp_avg,temp_max,temp_min,rainfall,humidity,solar_radiation,wind_speed,lat,lon
0,2024-01-01,Onion,Vegetables,Bihar,Bahadurganj APMC,4.0,Metric Tonnes,4100.0,4000.0,4200.0,...,5,13.96,21.72,8.22,0.0,72.05,6.05,1.57,25.67,86.93
1,2024-01-01,Onion,Vegetables,Bihar,Barahat APMC,4.0,Metric Tonnes,3500.0,3000.0,4000.0,...,5,13.93,21.52,7.95,0.0,69.86,10.69,1.57,24.88,86.92
2,2024-01-01,Onion,Vegetables,Bihar,Bhagwanpur Mandi APMC,15.0,Metric Tonnes,4100.0,4000.0,4200.0,...,5,15.47,24.23,8.86,0.0,54.51,5.38,1.47,26.12,85.38
3,2024-01-01,Onion,Vegetables,Bihar,Danapur APMC,30.0,Metric Tonnes,3000.0,2800.0,3200.0,...,5,15.19,23.63,7.64,0.0,49.75,6.39,1.44,25.42,85.17
4,2024-01-01,Onion,Vegetables,Bihar,"Gerabari, Korha Block APMC",4.0,Metric Tonnes,4900.0,4800.0,5000.0,...,5,14.39,21.85,8.98,0.0,74.98,8.25,1.65,25.55,87.57

In [11]:
missing = df[df["lat"].isna()][["district_name"]].drop_duplicates()
print("Missing districts:", missing.shape[0])
missing.head(20)

Missing districts: 1

                    district_name
100727  North and Middle Andaman

In [12]:
df.drop(["market_clean", "state_id", "UnitOfArrivals", "UnitOfPrice"], axis=1, inplace=True)

In [13]:
df.head()

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,district_name,temp_avg,temp_max,temp_min,rainfall,humidity,solar_radiation,wind_speed,lat,lon
0,2024-01-01,Onion,Vegetables,Bihar,Bahadurganj APMC,4.0,4100.0,4000.0,4200.0,Medium,...,Kishanganj,13.96,21.72,8.22,0.0,72.05,6.05,1.57,25.67,86.93
1,2024-01-01,Onion,Vegetables,Bihar,Barahat APMC,4.0,3500.0,3000.0,4000.0,Medium,...,Banka,13.93,21.52,7.95,0.0,69.86,10.69,1.57,24.88,86.92
2,2024-01-01,Onion,Vegetables,Bihar,Bhagwanpur Mandi APMC,15.0,4100.0,4000.0,4200.0,Medium,...,Muzaffarpur,15.47,24.23,8.86,0.0,54.51,5.38,1.47,26.12,85.38
3,2024-01-01,Onion,Vegetables,Bihar,Danapur APMC,30.0,3000.0,2800.0,3200.0,Medium,...,Patna,15.19,23.63,7.64,0.0,49.75,6.39,1.44,25.42,85.17
4,2024-01-01,Onion,Vegetables,Bihar,"Gerabari, Korha Block APMC",4.0,4900.0,4800.0,5000.0,Medium,...,Kaithar,14.39,21.85,8.98,0.0,74.98,8.25,1.65,25.55,87.57

In [14]:
import numpy as np

In [15]:
df["date"] = pd.to_datetime(df["date"])
df = df.sort_values(["Commodity", "Mandi", "date"]).reset_index(drop=True)

# **1. TEMPORAL FEATURES**

In [16]:
df["day"] = df["date"].dt.day
df["month"] = df["date"].dt.month
df["year"] = df["date"].dt.year
df["day_of_week"] = df["date"].dt.dayofweek
df["week_of_year"] = df["date"].dt.isocalendar().week.astype(int)
df["day_of_year"] = df["date"].dt.dayofyear
df["is_weekend"] = (df["day_of_week"] >= 5).astype(int)

# Fourier seasonal encoding
df["sin1"] = np.sin(2 * np.pi * df["day_of_year"] / 365)
df["cos1"] = np.cos(2 * np.pi * df["day_of_year"] / 365)
df["sin2"] = np.sin(4 * np.pi * df["day_of_year"] / 365)
df["cos2"] = np.cos(4 * np.pi * df["day_of_year"] / 365)

In [17]:
df.head()

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,month,year,day_of_week,week_of_year,day_of_year,is_weekend,sin1,cos1,sin2,cos2
0,2024-07-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,5000.0,4500.0,5000.0,Besrai,...,7,2024,1,29,198,0,-0.263665,-0.964614,0.508671,0.860961
1,2024-07-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.63,4600.0,4400.0,4600.0,Besrai,...,7,2024,2,29,199,0,-0.280231,-0.959933,0.538005,0.842942
2,2024-07-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,5200.0,4600.0,5200.0,Besrai,...,7,2024,3,29,200,0,-0.296713,-0.954967,0.566702,0.823923
3,2024-07-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,5000.0,4600.0,5000.0,Besrai,...,7,2024,4,29,201,0,-0.313107,-0.949718,0.594727,0.803928
4,2024-07-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,4400.0,4000.0,4400.0,Besrai,...,7,2024,5,29,202,1,-0.329408,-0.944188,0.622047,0.782980

# **2. PRICE LAG FEATURES**

In [18]:
group = df.groupby(["Commodity", "Mandi"])

for lag in [1, 3, 7, 14, 30]:
    df[f"modal_lag_{lag}"] = group["ModalPrice"].shift(lag)

In [19]:
df.head()

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,is_weekend,sin1,cos1,sin2,cos2,modal_lag_1,modal_lag_3,modal_lag_7,modal_lag_14,modal_lag_30
0,2024-07-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,5000.0,4500.0,5000.0,Besrai,...,0,-0.263665,-0.964614,0.508671,0.860961,NaN,NaN,NaN,NaN,NaN
1,2024-07-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.63,4600.0,4400.0,4600.0,Besrai,...,0,-0.280231,-0.959933,0.538005,0.842942,5000.0,NaN,NaN,NaN,NaN
2,2024-07-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,5200.0,4600.0,5200.0,Besrai,...,0,-0.296713,-0.954967,0.566702,0.823923,4600.0,NaN,NaN,NaN,NaN
3,2024-07-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,5000.0,4600.0,5000.0,Besrai,...,0,-0.313107,-0.949718,0.594727,0.803928,5200.0,5000.0,NaN,NaN,NaN
4,2024-07-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,4400.0,4000.0,4400.0,Besrai,...,1,-0.329408,-0.944188,0.622047,0.782980,5000.0,4600.0,NaN,NaN,NaN

# **3. PRICE ROLLING FEATURES**

In [20]:
for window in [3, 7, 14, 30]:
    df[f"rolling_mean_{window}"] = group["ModalPrice"].transform(lambda x: x.rolling(window).mean())
    df[f"rolling_std_{window}"] = group["ModalPrice"].transform(lambda x: x.rolling(window).std())

In [21]:
df.head(50)

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,modal_lag_14,modal_lag_30,rolling_mean_3,rolling_std_3,rolling_mean_7,rolling_std_7,rolling_mean_14,rolling_std_14,rolling_mean_30,rolling_std_30
0,2024-07-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,5000.0,4500.0,5000.0,Besrai,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-07-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.63,4600.0,4400.0,4600.0,Besrai,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-07-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,5200.0,4600.0,5200.0,Besrai,...,NaN,NaN,4933.333333,305.505046,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-07-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,4933.333333,305.505046,NaN,NaN,NaN,NaN,NaN,NaN
4,2024-07-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,4866.666667,416.333200,NaN,NaN,NaN,NaN,NaN,NaN
5,2024-07-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,4800.000000,346.410162,NaN,NaN,NaN,NaN,NaN,NaN
6,2024-07-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,4600.000000,346.410162,4800.000000,326.598632,NaN,NaN,NaN,NaN
7,2024-07-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,4600.000000,346.410162,4714.285714,343.649877,NaN,NaN,NaN,NaN
8,2024-07-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,4600.000000,346.410162,4771.428571,354.562104,NaN,NaN,NaN,NaN
9,2024-07-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,4800.000000,346.410162,4742.857143,320.713490,NaN,NaN,NaN,NaN
10,2024-07-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.80,5500.0,4500.0,5500.0,Besrai,...,NaN,NaN,5166.666667,288.675135,4814.285714,425.944329,NaN,NaN,NaN,NaN
11,2024-07-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,4600.0,4400.0,4600.0,Besrai,...,NaN,NaN,5033.333333,450.924975,4842.857143,399.404318,NaN,NaN,NaN,NaN
12,2024-07-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.92,4800.0,4600.0,4800.0,Besrai,...,NaN,NaN,4966.666667,472.581563,4814.285714,393.397896,NaN,NaN,NaN,NaN
13,2024-07-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,5600.0,5200.0,5600.0,Besrai,...,NaN,NaN,5000.000000,529.150262,4985.714286,441.318371,4892.857143,385.235763,NaN,NaN
14,2024-07-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.49,5500.0,5000.0,5500.0,Besrai,...,5000.0,NaN,5300.000000,435.889894,5142.857143,390.969491,4928.571429,417.738548,NaN,NaN
15,2024-07-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.43,4800.0,4600.0,4800.0,Besrai,...,4600.0,NaN,5300.000000,435.889894,5114.285714,409.994193,4942.857143,408.965460,NaN,NaN
16,2024-08-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.58,5500.0,5000.0,5500.0,Besrai,...,5200.0,NaN,5266.666667,404.145188,5185.714286,429.839394,4964.285714,430.754513,NaN,NaN
17,2024-08-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,5000.0,NaN,5433.333333,602.771377,5257.142857,522.357294,5035.714286,512.320727,NaN,NaN
18,2024-08-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,6500.0,5500.0,6500.0,Besrai,...,4400.0,NaN,6000.000000,500.000000,5528.571429,610.230245,5185.714286,609.990092,NaN,NaN
19,2024-08-04,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.59,6500.0,5500.0,6500.0,Besrai,...,5000.0,NaN,6333.333333,288.675135,5771.428571,610.230245,5292.857143,699.960752,NaN,NaN
20,2024-08-05,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,5000.0,4500.0,5000.0,Besrai,...,4400.0,NaN,6000.000000,866.025404,5685.714286,676.827333,5335.714286,658.211029,NaN,NaN
21,2024-08-06,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.16,5800.0,5500.0,5800.0,Besrai,...,4400.0,NaN,5766.666667,750.555350,5728.571429,672.592709,5435.714286,609.674747,NaN,NaN
22,2024-08-07,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,6500.0,5500.0,6500.0,Besrai,...,5000.0,NaN,5766.666667,750.555350,5971.428571,582.277957,5542.857143,657.166746,NaN,NaN
23,2024-08-08,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,5500.0,6500.0,Besrai,...,5000.0,NaN,6266.666667,404.145188,6114.285714,569.878851,5650.000000,683.599073,NaN,NaN
24,2024-08-09,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,6500.0,6000.0,6500.0,Besrai,...,5500.0,NaN,6500.000000,0.000000,6185.714286,584.318895,5721.428571,718.094242,NaN,NaN
25,2024-08-10,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.57,6500.0,5500.0,6500.0,Besrai,...,4600.0,NaN,6500.000000,0.000000,6185.714286,584.318895,5857.142857,667.618368,NaN,NaN
26,2024-08-11,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.71,6500.0,5500.0,6500.0,Besrai,...,4800.0,NaN,6500.000000,0.000000,6185.714286,584.318895,5978.571429,612.910549,NaN,NaN
27,2024-08-12,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5400.0,5000.0,5400.0,Besrai,...,5600.0,NaN,6133.333333,635.085296,6242.857143,454.082015,5964.285714,624.631760,NaN,NaN
28,2024-08-13,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,5600.0,5000.0,5600.0,Besrai,...,5500.0,NaN,5833.333333,585.946528,6214.285714,491.353815,5971.428571,619.464498,NaN,NaN
29,2024-08-14,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,7000.0,5600.0,7000.0,Besrai,...,4800.0,NaN,6000.000000,871.779789,6285.714286,569.878851,6128.571429,577.032957,5486.666667,775.367914
30,2024-08-15,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,5600.0,6500.0,Besrai,...,5500.0,5000.0,6366.666667,709.459888,6285.714286,569.878851,6200.000000,554.700196,5536.666667,791.107183
31,2024-08-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,6500.0,6000.0,6500.0,Besrai,...,6000.0,4600.0,6666.666667,288.675135,6285.714286,569.878851,6235.714286,556.924443,5600.000000,789.587409
32,2024-08-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.81,6500.0,6000.0,6500.0,Besrai,...,6500.0,5200.0,6500.000000,0.000000,6285.714286,569.878851,6235.714286,556.924443,5643.333333,802.445973
33,2024-08-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,7000.0,6000.0,7000.0,Besrai,...,6500.0,5000.0,6666.666667,288.675135,6357.142857,629.436634,6271.428571,590.213223,5710.000000,829.769390
34,2024-08-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,6000.0,5500.0,6000.0,Besrai,...,5000.0,4400.0,6500.000000,500.000000,6442.857143,506.152621,6342.857143,473.472094,5763.333333,793.283588
35,2024-08-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.86,5800.0,5500.0,5800.0,Besrai,...,5800.0,5000.0,6266.666667,642.910051,6471.428571,453.557368,6342.857143,473.472094,5790.000000,780.075151
36,2024-08-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,6500.0,6000.0,6500.0,Besrai,...,6500.0,4400.0,6100.000000,360.555128,6400.000000,391.578004,6342.857143,473.472094,5860.000000,744.450735
37,2024-08-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,6000.0,6500.0,Besrai,...,6500.0,4400.0,6266.666667,404.145188,6400.000000,391.578004,6342.857143,473.472094,5930.000000,699.827565
38,2024-08-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,5500.0,5000.0,5500.0,Besrai,...,6500.0,5000.0,6166.666667,577.350269,6257.142857,512.695956,6271.428571,520.988072,5946.666667,682.658764
39,2024-08-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,6000.0,5500.0,6000.0,Besrai,...,6500.0,5000.0,6000.000000,500.000000,6185.714286,508.030745,6235.714286,521.251664,5980.000000,658.839104
40,2024-08-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5600.0,6000.0,Besrai,...,6500.0,5500.0,5833.333333,288.675135,6042.857143,359.894164,6200.000000,518.874522,5996.666667,652.572275
41,2024-08-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5500.0,6000.0,Besrai,...,5400.0,4600.0,6000.000000,0.000000,6042.857143,359.894164,6242.857143,470.211549,6043.333333,596.936624
42,2024-08-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,5400.0,5000.0,5400.0,Besrai,...,5600.0,4800.0,5800.000000,346.410162,5985.714286,429.839394,6228.571429,493.696530,6063.333333,562.925446
43,2024-08-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.38,6000.0,5500.0,6000.0,Besrai,...,7000.0,5600.0,5800.000000,346.410162,5914.285714,367.099312,6157.142857,443.264612,6076.666667,556.270421
44,2024-08-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,6000.0,6500.0,Besrai,...,6500.0,5500.0,5966.666667,550.757055,5914.285714,367.099312,6157.142857,443.264612,6110.000000,550.454358
45,2024-08-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,6500.0,4800.0,6166.666667,288.675135,5985.714286,318.478526,6121.428571,433.551650,6150.000000,492.530412
46,2024-08-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6000.0,5600.0,6000.0,Besrai,...,6500.0,5500.0,6166.666667,288.675135,5985.714286,318.478526,6085.714286,420.360912,6166.666667,478.022747
47,2024-09-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,6500.0,6000.0,6500.0,Besrai,...,7000.0,6000.0,6166.666667,288.675135,6057.142857,373.528860,6050.000000,352.463855,6183.333333,480.720245
48,2024-09-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,6200.0,6000.0,6200.0,Besrai,...,6000.0,6500.0,6233.333333,251.661148,6085.714286,376.069902,6064.285714,354.329579,6173.333333,477.011771
49,2024-09-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6200.0,6000.0,6200.0,Besrai,...,5800.0,6500.0,6300.000000,173.205081,6200.000000,223.606798,6092.857143,347.439614,6163.333333,473.055609

# **4. VOLATILITY FEATURES**

In [22]:
df["price_range"] = df["MaxPrice"] - df["MinPrice"]
df["price_spread"] = df["MaxPrice"] - df["ModalPrice"]
df["norm_spread"] = df["price_range"] / (df["ModalPrice"] + 1)

df["volatility_7"] = df["rolling_std_7"]
df["volatility_30"] = df["rolling_std_30"]

df["zscore_7"] = (df["ModalPrice"] - df["rolling_mean_7"]) / (df["rolling_std_7"] + 1e-6)
df["momentum_7"] = df["ModalPrice"] - df["modal_lag_7"]
df["momentum_14"] = df["ModalPrice"] - df["modal_lag_14"]

In [23]:
df.head(50)

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,rolling_mean_30,rolling_std_30,price_range,price_spread,norm_spread,volatility_7,volatility_30,zscore_7,momentum_7,momentum_14
0,2024-07-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,5000.0,4500.0,5000.0,Besrai,...,NaN,NaN,500.0,0.0,0.099980,NaN,NaN,NaN,NaN,NaN
1,2024-07-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.63,4600.0,4400.0,4600.0,Besrai,...,NaN,NaN,200.0,0.0,0.043469,NaN,NaN,NaN,NaN,NaN
2,2024-07-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,5200.0,4600.0,5200.0,Besrai,...,NaN,NaN,600.0,0.0,0.115362,NaN,NaN,NaN,NaN,NaN
3,2024-07-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,400.0,0.0,0.079984,NaN,NaN,NaN,NaN,NaN
4,2024-07-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,400.0,0.0,0.090888,NaN,NaN,NaN,NaN,NaN
5,2024-07-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,400.0,0.0,0.079984,NaN,NaN,NaN,NaN,NaN
6,2024-07-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,400.0,0.0,0.090888,326.598632,NaN,-1.224745,NaN,NaN
7,2024-07-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,400.0,0.0,0.090888,343.649877,NaN,-0.914552,-600.0,NaN
8,2024-07-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,400.0,0.0,0.079984,354.562104,NaN,0.644658,400.0,NaN
9,2024-07-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,400.0,0.0,0.079984,320.713490,NaN,0.801784,-200.0,NaN
10,2024-07-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.80,5500.0,4500.0,5500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.181785,425.944329,NaN,1.609868,500.0,NaN
11,2024-07-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,4600.0,4400.0,4600.0,Besrai,...,NaN,NaN,200.0,0.0,0.043469,399.404318,NaN,-0.608048,200.0,NaN
12,2024-07-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.92,4800.0,4600.0,4800.0,Besrai,...,NaN,NaN,200.0,0.0,0.041658,393.397896,NaN,-0.036314,-200.0,NaN
13,2024-07-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,5600.0,5200.0,5600.0,Besrai,...,NaN,NaN,400.0,0.0,0.071416,441.318371,NaN,1.391933,1200.0,NaN
14,2024-07-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.49,5500.0,5000.0,5500.0,Besrai,...,NaN,NaN,500.0,0.0,0.090893,390.969491,NaN,0.913480,1100.0,500.0
15,2024-07-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.43,4800.0,4600.0,4800.0,Besrai,...,NaN,NaN,200.0,0.0,0.041658,409.994193,NaN,-0.766561,-200.0,200.0
16,2024-08-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.58,5500.0,5000.0,5500.0,Besrai,...,NaN,NaN,500.0,0.0,0.090893,429.839394,NaN,0.731170,500.0,300.0
17,2024-08-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,NaN,NaN,500.0,0.0,0.083319,522.357294,NaN,1.422125,500.0,1000.0
18,2024-08-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,6500.0,5500.0,6500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.153822,610.230245,NaN,1.591905,1900.0,2100.0
19,2024-08-04,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.59,6500.0,5500.0,6500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.153822,610.230245,NaN,1.193929,1700.0,1500.0
20,2024-08-05,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,5000.0,4500.0,5000.0,Besrai,...,NaN,NaN,500.0,0.0,0.099980,676.827333,NaN,-1.013130,-600.0,600.0
21,2024-08-06,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.16,5800.0,5500.0,5800.0,Besrai,...,NaN,NaN,300.0,0.0,0.051715,672.592709,NaN,0.106199,300.0,1400.0
22,2024-08-07,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,6500.0,5500.0,6500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.153822,582.277957,NaN,0.907765,1700.0,1500.0
23,2024-08-08,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,5500.0,6500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.153822,569.878851,NaN,0.676836,1000.0,1500.0
24,2024-08-09,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,6500.0,6000.0,6500.0,Besrai,...,NaN,NaN,500.0,0.0,0.076911,584.318895,NaN,0.537867,500.0,1000.0
25,2024-08-10,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.57,6500.0,5500.0,6500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.153822,584.318895,NaN,0.537867,0.0,1900.0
26,2024-08-11,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.71,6500.0,5500.0,6500.0,Besrai,...,NaN,NaN,1000.0,0.0,0.153822,584.318895,NaN,0.537867,0.0,1700.0
27,2024-08-12,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5400.0,5000.0,5400.0,Besrai,...,NaN,NaN,400.0,0.0,0.074060,454.082015,NaN,-1.856178,400.0,-200.0
28,2024-08-13,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,5600.0,5000.0,5600.0,Besrai,...,NaN,NaN,600.0,0.0,0.107124,491.353815,NaN,-1.250190,-200.0,100.0
29,2024-08-14,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,7000.0,5600.0,7000.0,Besrai,...,5486.666667,775.367914,1400.0,0.0,0.199971,569.878851,775.367914,1.253399,500.0,2200.0
30,2024-08-15,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,5600.0,6500.0,Besrai,...,5536.666667,791.107183,900.0,0.0,0.138440,569.878851,791.107183,0.376020,0.0,1000.0
31,2024-08-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,6500.0,6000.0,6500.0,Besrai,...,5600.000000,789.587409,500.0,0.0,0.076911,569.878851,789.587409,0.376020,0.0,500.0
32,2024-08-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.81,6500.0,6000.0,6500.0,Besrai,...,5643.333333,802.445973,500.0,0.0,0.076911,569.878851,802.445973,0.376020,0.0,0.0
33,2024-08-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,7000.0,6000.0,7000.0,Besrai,...,5710.000000,829.769390,1000.0,0.0,0.142837,629.436634,829.769390,1.021321,500.0,500.0
34,2024-08-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,6000.0,5500.0,6000.0,Besrai,...,5763.333333,793.283588,500.0,0.0,0.083319,506.152621,793.283588,-0.874948,600.0,1000.0
35,2024-08-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.86,5800.0,5500.0,5800.0,Besrai,...,5790.000000,780.075151,300.0,0.0,0.051715,453.557368,780.075151,-1.480361,200.0,0.0
36,2024-08-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,6500.0,6000.0,6500.0,Besrai,...,5860.000000,744.450735,500.0,0.0,0.076911,391.578004,744.450735,0.255377,-500.0,0.0
37,2024-08-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,6000.0,6500.0,Besrai,...,5930.000000,699.827565,500.0,0.0,0.076911,391.578004,699.827565,0.255377,0.0,0.0
38,2024-08-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,5500.0,5000.0,5500.0,Besrai,...,5946.666667,682.658764,500.0,0.0,0.090893,512.695956,682.658764,-1.476787,-1000.0,-1000.0
39,2024-08-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,6000.0,5500.0,6000.0,Besrai,...,5980.000000,658.839104,500.0,0.0,0.083319,508.030745,658.839104,-0.365557,-500.0,-500.0
40,2024-08-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5600.0,6000.0,Besrai,...,5996.666667,652.572275,400.0,0.0,0.066656,359.894164,652.572275,-0.119083,-1000.0,-500.0
41,2024-08-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5500.0,6000.0,Besrai,...,6043.333333,596.936624,500.0,0.0,0.083319,359.894164,596.936624,-0.119083,0.0,600.0
42,2024-08-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,5400.0,5000.0,5400.0,Besrai,...,6063.333333,562.925446,400.0,0.0,0.074060,429.839394,562.925446,-1.362635,-400.0,-200.0
43,2024-08-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.38,6000.0,5500.0,6000.0,Besrai,...,6076.666667,556.270421,500.0,0.0,0.083319,367.099312,556.270421,0.233491,-500.0,-1000.0
44,2024-08-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,6000.0,6500.0,Besrai,...,6110.000000,550.454358,500.0,0.0,0.076911,367.099312,550.454358,1.595520,0.0,0.0
45,2024-08-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,6150.000000,492.530412,500.0,0.0,0.083319,318.478526,492.530412,0.044856,500.0,-500.0
46,2024-08-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6000.0,5600.0,6000.0,Besrai,...,6166.666667,478.022747,400.0,0.0,0.066656,318.478526,478.022747,0.044856,0.0,-500.0
47,2024-09-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,6500.0,6000.0,6500.0,Besrai,...,6183.333333,480.720245,500.0,0.0,0.076911,373.528860,480.720245,1.185604,500.0,-500.0
48,2024-09-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,6200.0,6000.0,6200.0,Besrai,...,6173.333333,477.011771,200.0,0.0,0.032253,376.069902,477.011771,0.303895,200.0,200.0
49,2024-09-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6200.0,6000.0,6200.0,Besrai,...,6163.333333,473.055609,200.0,0.0,0.032253,223.606798,473.055609,0.000000,800.0,400.0

# **5. ARRIVAL FEATURES**

In [24]:
for lag in [1, 3, 7, 14]:
    df[f"arrivals_lag_{lag}"] = group["Arrivals"].shift(lag)

for window in [7, 30]:
    df[f"arrivals_avg_{window}"] = group["Arrivals"].transform(lambda x: x.rolling(window).mean())

df["arrival_change_7"] = df["Arrivals"] - df["arrivals_lag_7"]

In [25]:
df.head(50)

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,zscore_7,momentum_7,momentum_14,arrivals_lag_1,arrivals_lag_3,arrivals_lag_7,arrivals_lag_14,arrivals_avg_7,arrivals_avg_30,arrival_change_7
0,2024-07-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,5000.0,4500.0,5000.0,Besrai,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-07-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.63,4600.0,4400.0,4600.0,Besrai,...,NaN,NaN,NaN,0.65,NaN,NaN,NaN,NaN,NaN,NaN
2,2024-07-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,5200.0,4600.0,5200.0,Besrai,...,NaN,NaN,NaN,0.63,NaN,NaN,NaN,NaN,NaN,NaN
3,2024-07-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,NaN,0.48,0.65,NaN,NaN,NaN,NaN,NaN
4,2024-07-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,NaN,0.61,0.63,NaN,NaN,NaN,NaN,NaN
5,2024-07-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,NaN,0.62,0.48,NaN,NaN,NaN,NaN,NaN
6,2024-07-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,4400.0,4000.0,4400.0,Besrai,...,-1.224745,NaN,NaN,0.88,0.61,NaN,NaN,0.640000,NaN,NaN
7,2024-07-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,4400.0,4000.0,4400.0,Besrai,...,-0.914552,-600.0,NaN,0.61,0.62,0.65,NaN,0.654286,NaN,0.10
8,2024-07-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,5000.0,4600.0,5000.0,Besrai,...,0.644658,400.0,NaN,0.75,0.88,0.63,NaN,0.670000,NaN,0.11
9,2024-07-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5000.0,4600.0,5000.0,Besrai,...,0.801784,-200.0,NaN,0.74,0.61,0.48,NaN,0.678571,NaN,0.06
10,2024-07-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.80,5500.0,4500.0,5500.0,Besrai,...,1.609868,500.0,NaN,0.54,0.75,0.61,NaN,0.705714,NaN,0.19
11,2024-07-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,4600.0,4400.0,4600.0,Besrai,...,-0.608048,200.0,NaN,0.80,0.74,0.62,NaN,0.720000,NaN,0.10
12,2024-07-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.92,4800.0,4600.0,4800.0,Besrai,...,-0.036314,-200.0,NaN,0.72,0.54,0.88,NaN,0.725714,NaN,0.04
13,2024-07-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,5600.0,5200.0,5600.0,Besrai,...,1.391933,1200.0,NaN,0.92,0.80,0.61,NaN,0.741429,NaN,0.11
14,2024-07-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.49,5500.0,5000.0,5500.0,Besrai,...,0.913480,1100.0,500.0,0.72,0.72,0.75,0.65,0.704286,NaN,-0.26
15,2024-07-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.43,4800.0,4600.0,4800.0,Besrai,...,-0.766561,-200.0,200.0,0.49,0.92,0.74,0.63,0.660000,NaN,-0.31
16,2024-08-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.58,5500.0,5000.0,5500.0,Besrai,...,0.731170,500.0,300.0,0.43,0.72,0.54,0.48,0.665714,NaN,0.04
17,2024-08-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,1.422125,500.0,1000.0,0.58,0.49,0.80,0.61,0.662857,NaN,-0.02
18,2024-08-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,6500.0,5500.0,6500.0,Besrai,...,1.591905,1900.0,2100.0,0.78,0.43,0.72,0.62,0.685714,NaN,0.16
19,2024-08-04,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.59,6500.0,5500.0,6500.0,Besrai,...,1.193929,1700.0,1500.0,0.88,0.58,0.92,0.88,0.638571,NaN,-0.33
20,2024-08-05,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,5000.0,4500.0,5000.0,Besrai,...,-1.013130,-600.0,600.0,0.59,0.78,0.72,0.61,0.581429,NaN,-0.40
21,2024-08-06,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.16,5800.0,5500.0,5800.0,Besrai,...,0.106199,300.0,1400.0,0.32,0.88,0.49,0.75,0.534286,NaN,-0.33
22,2024-08-07,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,6500.0,5500.0,6500.0,Besrai,...,0.907765,1700.0,1500.0,0.16,0.59,0.43,0.74,0.561429,NaN,0.19
23,2024-08-08,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,5500.0,6500.0,Besrai,...,0.676836,1000.0,1500.0,0.62,0.32,0.58,0.54,0.547143,NaN,-0.10
24,2024-08-09,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,6500.0,6000.0,6500.0,Besrai,...,0.537867,500.0,1000.0,0.48,0.16,0.78,0.80,0.481429,NaN,-0.46
25,2024-08-10,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.57,6500.0,5500.0,6500.0,Besrai,...,0.537867,0.0,1900.0,0.32,0.62,0.88,0.72,0.437143,NaN,-0.31
26,2024-08-11,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.71,6500.0,5500.0,6500.0,Besrai,...,0.537867,0.0,1700.0,0.57,0.48,0.59,0.92,0.454286,NaN,0.12
27,2024-08-12,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5400.0,5000.0,5400.0,Besrai,...,-1.856178,400.0,-200.0,0.71,0.32,0.32,0.72,0.485714,NaN,0.22
28,2024-08-13,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,5600.0,5000.0,5600.0,Besrai,...,-1.250190,-200.0,100.0,0.54,0.57,0.16,0.49,0.571429,NaN,0.60
29,2024-08-14,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,7000.0,5600.0,7000.0,Besrai,...,1.253399,500.0,2200.0,0.76,0.71,0.62,0.43,0.581429,0.619667,0.07
30,2024-08-15,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,5600.0,6500.0,Besrai,...,0.376020,0.0,1000.0,0.69,0.54,0.48,0.58,0.612857,0.621333,0.22
31,2024-08-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,6500.0,6000.0,6500.0,Besrai,...,0.376020,0.0,500.0,0.70,0.76,0.32,0.78,0.670000,0.624333,0.40
32,2024-08-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.81,6500.0,6000.0,6500.0,Besrai,...,0.376020,0.0,0.0,0.72,0.69,0.57,0.88,0.704286,0.635333,0.24
33,2024-08-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,7000.0,6000.0,7000.0,Besrai,...,1.021321,500.0,500.0,0.81,0.70,0.71,0.59,0.745714,0.648333,0.29
34,2024-08-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,6000.0,5500.0,6000.0,Besrai,...,-0.874948,600.0,1000.0,1.00,0.72,0.54,0.32,0.775714,0.652667,0.21
35,2024-08-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.86,5800.0,5500.0,5800.0,Besrai,...,-1.480361,200.0,0.0,0.75,0.81,0.76,0.16,0.790000,0.652000,0.10
36,2024-08-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,6500.0,6000.0,6500.0,Besrai,...,0.255377,-500.0,0.0,0.86,1.00,0.69,0.62,0.790000,0.654667,0.00
37,2024-08-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,6000.0,6500.0,Besrai,...,0.255377,0.0,0.0,0.69,0.75,0.70,0.48,0.758571,0.645667,-0.22
38,2024-08-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,5500.0,5000.0,5500.0,Besrai,...,-1.476787,-1000.0,-1000.0,0.48,0.86,0.72,0.32,0.754286,0.644000,-0.03
39,2024-08-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,6000.0,5500.0,6000.0,Besrai,...,-0.365557,-500.0,-500.0,0.69,0.69,0.81,0.57,0.731429,0.647667,-0.16
40,2024-08-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5600.0,6000.0,Besrai,...,-0.119083,-1000.0,-500.0,0.65,0.48,1.00,0.71,0.708571,0.649000,-0.16
41,2024-08-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5500.0,6000.0,Besrai,...,-0.119083,0.0,600.0,0.84,0.69,0.75,0.54,0.721429,0.653000,0.09
42,2024-08-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,5400.0,5000.0,5400.0,Besrai,...,-1.362635,-400.0,-200.0,0.84,0.65,0.86,0.76,0.698571,0.645667,-0.16
43,2024-08-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.38,6000.0,5500.0,6000.0,Besrai,...,0.233491,-500.0,-1000.0,0.70,0.84,0.69,0.69,0.654286,0.634333,-0.31
44,2024-08-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,6000.0,6500.0,Besrai,...,1.595520,0.0,0.0,0.38,0.84,0.48,0.70,0.685714,0.641333,0.22
45,2024-08-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,0.044856,500.0,-500.0,0.70,0.70,0.69,0.72,0.698571,0.653000,0.09
46,2024-08-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6000.0,5600.0,6000.0,Besrai,...,0.044856,0.0,-500.0,0.78,0.38,0.65,0.81,0.711429,0.658333,0.09
47,2024-09-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,6500.0,6000.0,6500.0,Besrai,...,1.185604,500.0,-500.0,0.74,0.70,0.84,1.00,0.734286,0.665667,0.16
48,2024-09-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,6200.0,6000.0,6200.0,Besrai,...,0.303895,200.0,200.0,1.00,0.78,0.84,0.75,0.722857,0.661667,-0.08
49,2024-09-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6200.0,6000.0,6200.0,Besrai,...,0.000000,800.0,400.0,0.76,0.74,0.70,0.86,0.728571,0.666667,0.04

# **6. WEATHER FEATURES (AND ANOMALIES)**

In [26]:
df["temp_range"] = df["temp_max"] - df["temp_min"]
df["rain_intensity"] = df["rainfall"] / 24

# Rolling 30-day climate trend
df["temp_avg_30"] = group["temp_avg"].transform(lambda x: x.rolling(30).mean())
df["rain_avg_30"] = group["rainfall"].transform(lambda x: x.rolling(30).mean())

df["temp_anomaly"] = df["temp_avg"] - df["temp_avg_30"]
df["rain_anomaly"] = df["rainfall"] - df["rain_avg_30"]

In [27]:
df.head(50)

,date,Commodity,CropGroup,State,Mandi,Arrivals,ModalPrice,MinPrice,MaxPrice,Variety,...,arrivals_lag_14,arrivals_avg_7,arrivals_avg_30,arrival_change_7,temp_range,rain_intensity,temp_avg_30,rain_avg_30,temp_anomaly,rain_anomaly
0,2024-07-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,5000.0,4500.0,5000.0,Besrai,...,NaN,NaN,NaN,NaN,7.95,0.040833,NaN,NaN,NaN,NaN
1,2024-07-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.63,4600.0,4400.0,4600.0,Besrai,...,NaN,NaN,NaN,NaN,8.03,0.077917,NaN,NaN,NaN,NaN
2,2024-07-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,5200.0,4600.0,5200.0,Besrai,...,NaN,NaN,NaN,NaN,7.69,0.198750,NaN,NaN,NaN,NaN
3,2024-07-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,NaN,NaN,7.24,0.127917,NaN,NaN,NaN,NaN
4,2024-07-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,4400.0,4000.0,4400.0,Besrai,...,NaN,NaN,NaN,NaN,9.83,0.175000,NaN,NaN,NaN,NaN
5,2024-07-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,5000.0,4600.0,5000.0,Besrai,...,NaN,NaN,NaN,NaN,11.10,0.080000,NaN,NaN,NaN,NaN
6,2024-07-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.61,4400.0,4000.0,4400.0,Besrai,...,NaN,0.640000,NaN,NaN,11.43,0.036250,NaN,NaN,NaN,NaN
7,2024-07-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,4400.0,4000.0,4400.0,Besrai,...,NaN,0.654286,NaN,0.10,10.65,0.030833,NaN,NaN,NaN,NaN
8,2024-07-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,5000.0,4600.0,5000.0,Besrai,...,NaN,0.670000,NaN,0.11,10.85,0.010833,NaN,NaN,NaN,NaN
9,2024-07-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5000.0,4600.0,5000.0,Besrai,...,NaN,0.678571,NaN,0.06,11.09,0.116250,NaN,NaN,NaN,NaN
10,2024-07-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.80,5500.0,4500.0,5500.0,Besrai,...,NaN,0.705714,NaN,0.19,8.97,0.038333,NaN,NaN,NaN,NaN
11,2024-07-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,4600.0,4400.0,4600.0,Besrai,...,NaN,0.720000,NaN,0.10,10.40,0.002083,NaN,NaN,NaN,NaN
12,2024-07-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.92,4800.0,4600.0,4800.0,Besrai,...,NaN,0.725714,NaN,0.04,11.23,0.000000,NaN,NaN,NaN,NaN
13,2024-07-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,5600.0,5200.0,5600.0,Besrai,...,NaN,0.741429,NaN,0.11,11.83,0.082083,NaN,NaN,NaN,NaN
14,2024-07-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.49,5500.0,5000.0,5500.0,Besrai,...,0.65,0.704286,NaN,-0.26,7.09,0.057917,NaN,NaN,NaN,NaN
15,2024-07-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.43,4800.0,4600.0,4800.0,Besrai,...,0.63,0.660000,NaN,-0.31,11.08,0.220417,NaN,NaN,NaN,NaN
16,2024-08-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.58,5500.0,5000.0,5500.0,Besrai,...,0.48,0.665714,NaN,0.04,10.69,0.175000,NaN,NaN,NaN,NaN
17,2024-08-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,0.61,0.662857,NaN,-0.02,10.53,0.020417,NaN,NaN,NaN,NaN
18,2024-08-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.88,6500.0,5500.0,6500.0,Besrai,...,0.62,0.685714,NaN,0.16,9.69,0.068750,NaN,NaN,NaN,NaN
19,2024-08-04,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.59,6500.0,5500.0,6500.0,Besrai,...,0.88,0.638571,NaN,-0.33,7.83,0.204167,NaN,NaN,NaN,NaN
20,2024-08-05,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,5000.0,4500.0,5000.0,Besrai,...,0.61,0.581429,NaN,-0.40,12.31,0.177083,NaN,NaN,NaN,NaN
21,2024-08-06,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.16,5800.0,5500.0,5800.0,Besrai,...,0.75,0.534286,NaN,-0.33,6.15,0.485833,NaN,NaN,NaN,NaN
22,2024-08-07,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.62,6500.0,5500.0,6500.0,Besrai,...,0.74,0.561429,NaN,0.19,6.51,0.296250,NaN,NaN,NaN,NaN
23,2024-08-08,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,5500.0,6500.0,Besrai,...,0.54,0.547143,NaN,-0.10,8.94,0.111667,NaN,NaN,NaN,NaN
24,2024-08-09,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.32,6500.0,6000.0,6500.0,Besrai,...,0.80,0.481429,NaN,-0.46,9.63,0.528333,NaN,NaN,NaN,NaN
25,2024-08-10,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.57,6500.0,5500.0,6500.0,Besrai,...,0.72,0.437143,NaN,-0.31,6.75,1.132500,NaN,NaN,NaN,NaN
26,2024-08-11,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.71,6500.0,5500.0,6500.0,Besrai,...,0.92,0.454286,NaN,0.12,6.03,1.047083,NaN,NaN,NaN,NaN
27,2024-08-12,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.54,5400.0,5000.0,5400.0,Besrai,...,0.72,0.485714,NaN,0.22,7.06,0.507083,NaN,NaN,NaN,NaN
28,2024-08-13,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,5600.0,5000.0,5600.0,Besrai,...,0.49,0.571429,NaN,0.60,7.30,0.450000,NaN,NaN,NaN,NaN
29,2024-08-14,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,7000.0,5600.0,7000.0,Besrai,...,0.43,0.581429,0.619667,0.07,7.10,0.245417,26.363667,5.396000,0.356333,0.494000
30,2024-08-15,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,5600.0,6500.0,Besrai,...,0.58,0.612857,0.621333,0.22,8.37,0.480417,26.383667,5.747667,0.196333,5.782333
31,2024-08-16,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.72,6500.0,6000.0,6500.0,Besrai,...,0.78,0.670000,0.624333,0.40,7.64,0.322083,26.424333,5.943000,0.115667,1.787000
32,2024-08-17,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.81,6500.0,6000.0,6500.0,Besrai,...,0.88,0.704286,0.635333,0.24,5.99,0.092500,26.470000,5.858000,0.070000,-3.638000
33,2024-08-18,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,7000.0,6000.0,7000.0,Besrai,...,0.59,0.745714,0.648333,0.29,7.56,0.120417,26.504000,5.852000,0.076000,-2.962000
34,2024-08-19,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.75,6000.0,5500.0,6000.0,Besrai,...,0.32,0.775714,0.652667,0.21,6.67,0.071250,26.500000,5.769000,-0.110000,-4.059000
35,2024-08-20,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.86,5800.0,5500.0,5800.0,Besrai,...,0.16,0.790000,0.652000,0.10,7.62,0.315000,26.507000,5.957000,-0.157000,1.603000
36,2024-08-21,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,6500.0,6000.0,6500.0,Besrai,...,0.62,0.790000,0.654667,0.00,6.83,0.065000,26.481000,5.980000,-0.951000,-4.420000
37,2024-08-22,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.48,6500.0,6000.0,6500.0,Besrai,...,0.48,0.758571,0.645667,-0.22,8.00,0.000417,26.433333,5.955667,-1.523333,-5.945667
38,2024-08-23,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.69,5500.0,5000.0,5500.0,Besrai,...,0.32,0.754286,0.644000,-0.03,9.96,0.000000,26.426000,5.947000,-0.506000,-5.947000
39,2024-08-24,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.65,6000.0,5500.0,6000.0,Besrai,...,0.57,0.731429,0.647667,-0.16,9.45,0.021667,26.394000,5.871333,-0.734000,-5.351333
40,2024-08-25,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5600.0,6000.0,Besrai,...,0.71,0.708571,0.649000,-0.16,9.82,0.024167,26.365000,5.860000,-0.815000,-5.280000
41,2024-08-26,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.84,6000.0,5500.0,6000.0,Besrai,...,0.54,0.721429,0.653000,0.09,10.59,0.002917,26.329333,5.860667,-0.499333,-5.790667
42,2024-08-27,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,5400.0,5000.0,5400.0,Besrai,...,0.76,0.698571,0.645667,-0.16,9.72,0.116250,26.297667,5.953667,-0.527667,-3.163667
43,2024-08-28,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.38,6000.0,5500.0,6000.0,Besrai,...,0.69,0.654286,0.634333,-0.31,9.32,0.016667,26.221333,5.901333,-0.951333,-5.501333
44,2024-08-29,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.70,6500.0,6000.0,6500.0,Besrai,...,0.70,0.685714,0.641333,0.22,8.71,0.324583,26.196000,6.114667,-1.046000,1.675333
45,2024-08-30,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.78,6000.0,5500.0,6000.0,Besrai,...,0.72,0.698571,0.653000,0.09,6.32,0.383333,26.118667,6.245000,-1.328667,2.955000
46,2024-08-31,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6000.0,5600.0,6000.0,Besrai,...,0.81,0.711429,0.658333,0.09,8.50,0.222083,26.034333,6.282667,-1.164333,-0.952667
47,2024-09-01,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,1.00,6500.0,6000.0,6500.0,Besrai,...,1.00,0.734286,0.665667,0.16,9.29,0.119583,25.988333,6.362000,-0.648333,-3.492000
48,2024-09-02,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.76,6200.0,6000.0,6200.0,Besrai,...,0.75,0.722857,0.661667,-0.08,11.49,0.037500,25.969000,6.337000,-0.129000,-5.437000
49,2024-09-03,Banana,Fruits,Tamil Nadu,AJattihalli(Uzhavar Sandhai ) APMC,0.74,6200.0,6000.0,6200.0,Besrai,...,0.86,0.728571,0.666667,0.04,10.66,0.149167,25.987333,6.293000,0.072667,-2.713000

# **7. Combined Spatial Features (Raw + Transformed)**

In [28]:
# --- Spatial Features (Combined Raw + Sin/Cos) ---
df["lat"] = df["lat"].astype(float)
df["lon"] = df["lon"].astype(float)

df["lat_sin"] = np.sin(np.radians(df["lat"]))
df["lat_cos"] = np.cos(np.radians(df["lat"]))
df["lon_sin"] = np.sin(np.radians(df["lon"]))
df["lon_cos"] = np.cos(np.radians(df["lon"]))

spatial_features = [
    "lat", "lon",
    "lat_sin", "lat_cos",
    "lon_sin", "lon_cos"
]

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2748688 entries, 0 to 2748687
Data columns (total 70 columns):
 #   Column            Dtype
---  ------            -----
 0   date              datetime64[ns]
 1   Commodity         object
 2   CropGroup         object
 3   State             object
 4   Mandi             object
 5   Arrivals          float64
 6   ModalPrice        float64
 7   MinPrice          float64
 8   MaxPrice          float64
 9   Variety           object
 10  Grade             object
 11  district_name     object
 12  temp_avg          float64
 13  temp_max          float64
 14  temp_min          float64
 15  rainfall          float64
 16  humidity          float64
 17  solar_radiation   float64
 18  wind_speed        float64
 19  lat               float64
 20  lon               float64
 21  day               int32
 22  month             int32
 23  year              int32
 24  day_of_week       int32
 25  week_of_year      int64
 26  day_of_year       int32
 27  is_weekend        int64
 28  sin1              float64
 29  cos1              float64
 30  sin2              float64
 31  cos2              float64
 32  modal_lag_1       float64
 33  modal_lag_3       float64
 34  modal_lag_7       float64
 35  modal_lag_14      float64
 36  modal_lag_30      float64
 37  rolling_mean_3    float64
 38  rolling_std_3     float64
 39  rolling_mean_7    float64
 40  rolling_std_7     float64
 41  rolling_mean_14   float64
 42  rolling_std_14    float64
 43  rolling_mean_30   float64
 44  rolling_std_30    float64
 45  price_range       float64
 46  price_spread      float64
 47  norm_spread       float64
 48  volatility_7      float64
 49  volatility_30     float64
 50  zscore_7          float64
 51  momentum_7        float64
 52  momentum_14       float64
 53  arrivals_lag_1    float64
 54  arrivals_lag_3    float64
 55  arrivals_lag_7    float64
 56  arrivals_lag_14   float64
 57  arrivals_avg_7    float64
 58  arrivals_avg_30   float64
 59  arrival_change_7  float64
 60  temp_range        float64
 61  rain_intensity    float64
 62  temp_avg_30       float64
 63  rain_avg_30       float64
 64  temp_anomaly      float64
 65  rain_anomaly      float64
 66  lat_sin           float64
 67  lat_cos           float64
 68  lon_sin           float64
 69  lon_cos           float64
dtypes: datetime64[ns](1), float64(55), int32(5), int64(2), object(7)
memory usage: 1.4+ GB

In [30]:
df.isna().sum()

date                 0
Commodity            0
CropGroup            0
State                0
Mandi                0
                 ...
rain_anomaly    230763
lat_sin             99
lat_cos             99
lon_sin             99
lon_cos             99
Length: 70, dtype: int64

In [31]:
df = df.dropna().reset_index(drop=True)

In [32]:
df.shape

(2510944, 70)

# **✅ STEP 2: Moirai + Uni2TS Dataset Schema Preparation**

# **1. Create the SERIES ID (Critical Step)**

In [33]:
df = df.sort_values(["Commodity", "Mandi", "date"]).reset_index(drop=True)

df["series_id"], series_mapping = pd.factorize(
    df["Commodity"].astype(str) + " | " + df["Mandi"].astype(str)
)

# **2. Define STATIC features**

In [34]:

#Static Categorical (embed as integers)
static_cat_cols = ["Commodity", "CropGroup", "State", "district_name", "Mandi", "Variety", "Grade"]

# Encode to integer IDs
for col in static_cat_cols:
    df[col + "_id"] = df[col].astype("category").cat.codes

#Static Numeric (spatial)
static_num_cols = ["lat_sin", "lat_cos", "lon_sin", "lon_cos"]

# **3. Define DYNAMIC features**

In [35]:
dynamic_num_cols = [
    # price-based
    "MinPrice","MaxPrice","ModalPrice",
    "price_range","price_spread","norm_spread",
    "volatility_7","volatility_30","zscore_7",
    "momentum_7","momentum_14",

    # arrivals (supply)
    "Arrivals","arrivals_lag_1","arrivals_lag_3","arrivals_lag_7","arrivals_lag_14",
    "arrivals_avg_7","arrivals_avg_30","arrival_change_7",

    # weather
    "temp_avg","temp_max","temp_min","rainfall","humidity","solar_radiation","wind_speed",
    "temp_range","rain_intensity","temp_avg_30","rain_avg_30",
    "temp_anomaly","rain_anomaly",

    # lags
    "modal_lag_1","modal_lag_3","modal_lag_7","modal_lag_14","modal_lag_30",

    # rolling windows
    "rolling_mean_3","rolling_std_3",
    "rolling_mean_7","rolling_std_7",
    "rolling_mean_14","rolling_std_14",
    "rolling_mean_30","rolling_std_30",

    # time features
    "day","month","year","day_of_week","week_of_year",
    "day_of_year","is_weekend",
    "sin1","cos1","sin2","cos2",
]

In [36]:
target_col = "ModalPrice"

In [37]:
unused = list(set(df.columns.to_list()) - set(dynamic_num_cols))

In [38]:
unused

['Mandi',
 'Grade_id',
 'lon_sin',
 'lat_cos',
 'Variety',
 'State_id',
 'Commodity_id',
 'date',
 'lat_sin',
 'CropGroup_id',
 'district_name_id',
 'district_name',
 'State',
 'Commodity',
 'lon_cos',
 'lat',
 'Grade',
 'Variety_id',
 'lon',
 'Mandi_id',
 'CropGroup',
 'series_id']

In [54]:
df.columns.to_list()

['date',
 'Commodity',
 'CropGroup',
 'State',
 'Mandi',
 'Arrivals',
 'ModalPrice',
 'MinPrice',
 'MaxPrice',
 'Variety',
 'Grade',
 'district_name',
 'temp_avg',
 'temp_max',
 'temp_min',
 'rainfall',
 'humidity',
 'solar_radiation',
 'wind_speed',
 'lat',
 'lon',
 'day',
 'month',
 'year',
 'day_of_week',
 'week_of_year',
 'day_of_year',
 'is_weekend',
 'sin1',
 'cos1',
 'sin2',
 'cos2',
 'modal_lag_1',
 'modal_lag_3',
 'modal_lag_7',
 'modal_lag_14',
 'modal_lag_30',
 'rolling_mean_3',
 'rolling_std_3',
 'rolling_mean_7',
 'rolling_std_7',
 'rolling_mean_14',
 'rolling_std_14',
 'rolling_mean_30',
 'rolling_std_30',
 'price_range',
 'price_spread',
 'norm_spread',
 'volatility_7',
 'volatility_30',
 'zscore_7',
 'momentum_7',
 'momentum_14',
 'arrivals_lag_1',
 'arrivals_lag_3',
 'arrivals_lag_7',
 'arrivals_lag_14',
 'arrivals_avg_7',
 'arrivals_avg_30',
 'arrival_change_7',
 'temp_range',
 'rain_intensity',
 'temp_avg_30',
 'rain_avg_30',
 'temp_anomaly',
 'rain_anomaly',
 'lat_sin',
 'lat_cos',
 'lon_sin',
 'lon_cos',
 'series_id',
 'Commodity_id',
 'CropGroup_id',
 'State_id',
 'district_name_id',
 'Mandi_id',
 'Variety_id',
 'Grade_id']

In [55]:
df.to_csv("FeatureFullData.csv", index=False)